### PR TITLE
template deployments to be able to use different image for prod/stg

### PR DESCRIPTION
**Pull request by rpitonak**
I have added two new hooks:

- branch `master` -> `docker.io/usercont/packit-service:stg`
- branch `stable` -> `docker.io/usercont/packit-service:prod`

https://cloud.docker.com/u/usercont/repository/docker/usercont/packit-service/builds

### CODE REVIEW

**Comment by TomasTomecek** [comment]
branch `master` -> `:stg`
branch `stable` -> `:prod`

consistency :D

**Comment by rpitonak** [comment]
> branch `master` -> `:stg`
> branch `stable` -> `:prod`
> 
> consistency :D

It is because of playbooks :D

**Comment by rpitonak** [comment]
just testing and there are some troubles so please wait with the merge.

PS: @lachmanfrantisek please can you sync labels for this repo?

**Comment by rpitonak** [comment]
Tested on stg. PTAL.

**Comment by lachmanfrantisek** [comment]
> PS: @lachmanfrantisek please can you sync labels for this repo?

I am on it.

```
tool update-labels -r user-cont/kwaciaren packit-service-deployment
```

(I only need to fix some issues manually.)

**Pull request merged**
