### PR TITLE
add sentry secret

### PR DESCRIPTION
**Pull request by TomasTomecek**
also:
```
remove req on ansible 2.7
ansible-2.8.5-1.fc30.noarch works well for me
```

### CODE REVIEW

**Comment by jpopelka** [comment]
I'm pretty sure I tried `ansible-2.8.5-1.fc30` and it didn't work for me, so can you put it in a different PR please?

**Comment by TomasTomecek** [comment]
k

**Comment by TomasTomecek** [comment]
done, praise upsint and `git rebase -i`

**Comment by jpopelka** [comment]
> I'm pretty sure I tried `ansible-2.8.5-1.fc30` and it didn't work for me

Ok, so that must have been `2.8.4`, because `2.8.5` obviously works. I owe you a beer.

**Pull request merged**
