### PR TITLE
require ansible >= 2.8

### PR DESCRIPTION
**Pull request by TomasTomecek**
ansible-2.8.5-1.fc30.noarch works well for me

### CODE REVIEW

**Comment by jpopelka** [comment]
Woohoo, you're right, 2.8.5 includes [backported fix](https://github.com/ansible/ansible/commit/9fe0971004b94ac1b042e81efddf256125c9e7f2) for [the issue](https://github.com/ansible/ansible/issues/56640).

Can we now change all occurrences of `verify_ssl` to `validate_certs`?

**Comment by jpopelka** [comment]
One more change (in all playbooks) please. This now works too:
```diff
diff --git a/Makefile b/Makefile
index 4df57ed..10f6e4c 100644
--- a/Makefile
+++ b/Makefile
@@ -7,7 +7,7 @@ send-release-event:
        curl -d "@test_data/release_event.json" -H "Content-Type: application/json" -X POST http://$(shell oc get svc packit-service -o json | jq -r .spec.clusterIP)/webhooks/github/release
 
 deploy:
-       ansible-playbook -vv playbooks/deploy.yml
+       ansible-playbook -vv -c local -i localhost, playbooks/deploy.yml
 
 cleanup:
        ansible-playbook -vv playbooks/cleanup.yml
diff --git a/playbooks/deploy.yml b/playbooks/deploy.yml
index 2a76627..87ce72d 100644
--- a/playbooks/deploy.yml
+++ b/playbooks/deploy.yml
@@ -22,7 +22,7 @@
 
 ---
 - name: packit-service deployment
-  hosts: localhost
+  hosts: all
   vars:
     deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
     sandbox_namespace: "packit-{{ deployment }}-sandbox"
```

**Comment by TomasTomecek** [comment]
oh my, what have I done

**Comment by jpopelka** [comment]
muhehehehe :smiling_imp:

**Comment by TomasTomecek** [comment]
PTAL

**Comment by TomasTomecek** [comment]
now it even works on F30 - sorry Rado, no idea how your makbuk is set up

**Comment by TomasTomecek** [comment]
merging then, best of luck

**Pull request merged**
