### PR TITLE
deploy: make it work with ansible 2.7 & 2.8

### PR DESCRIPTION
**Pull request by TomasTomecek**
didn't try it though, should just work™

### CODE REVIEW

**Comment by rpitonak** [comment]
> Let's test in production then

[Tested](https://softwarefactory-project.io/zuul/t/local/build/5351de638f304287ae2db85a59be5b88) and unfortunately does not work.

**Comment by jpopelka** [comment]
> Tested and unfortunately does not work.

I've just noticed that [WE install ansible-2.7.10-1.fc30](https://github.com/packit-service/packit-service-zuul/blob/master/files/deploy-service.yaml#L10) - isn't that the cause why Zuul uses ansible-2.7? Wouldn't changing that to just `ansible` (unversioned, i.e. latest, i.e. 2.8.5) fix it too?

**Comment by rpitonak** [comment]
@jpopelka yes, you identify the problem but it is actually [here](https://github.com/packit-service/packit-service/blob/72b842218c1314ae2d90f0feb8a49ebdcc7bdafe/files/deployment.yaml#L10)

**Comment by jpopelka** [comment]
@rpitonak should I open a PR with the above-suggested change then?

**Pull request merged**
